# Generated by Django 3.2.8 on 2021-11-14 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_header',
            field=models.CharField(default='HEADER', max_length=250),
        ),
    ]
